### ISSUE TITLE
Check feedstocks against PyPI version

### ISSUE THREAD

**Issue by ocefpaf** [axiom-data-science/feedstockrot#1]
Not really an issue I just want to make sure that @pelson knows that this code exists.

I guess that the next steps are to output the changes (version, checksum, etc) and maybe create a PR with them.

@RSully feel free to close this.

**Comment by RSully** [comment]
Just a heads up, this currently checks against both PyPI and GitHub, and more sources could be added (say, BitBucket, Sourceforge, etc.).

**Comment by RSully** [comment]
I'll close this for now, feel free to use this issue as a discussion forum.

**Comment by pelson** [comment]
This is awesome. Thanks for putting this together @RSully and for pinging me @ocefpaf. Definitely something we should mention at the next conda-forge hangout to raise awareness. Maybe even part of the conda-forge docs (which are a little slim at present :wink:).
